<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>PogoAI</RootNamespace>
		<AssemblyName>PogoAI</AssemblyName>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>8.0</LangVersion>
		<PlatformTarget>x64</PlatformTarget>
		<Optimize>true</Optimize>
		<DebugType>pdbonly</DebugType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<ReleaseVersion>0.0.0.1</ReleaseVersion>
		<SynchReleaseVersion>false</SynchReleaseVersion>
		<Configurations>Release;Debug</Configurations>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugSymbols>true</DebugSymbols>
		<DefineConstants>TRACE;NDEBUG</DefineConstants>
		<WarningLevel>4</WarningLevel>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>TRACE;DEBUG_REACTION;DEBUG;NETFRAMEWORK;NET472;</DefineConstants>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<DebugType>full</DebugType>
	</PropertyGroup>	
	<ItemGroup>
		<PackageReference Include="Lib.Harmony" Version="2.3.3" ExcludeAssets="runtime" />		
	</ItemGroup>	
	<ItemGroup>
	  <Reference Include="Assembly-CSharp">
	    <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
	  </Reference>
	  <Reference Include="Mono.Security">
	    <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Mono.Security.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Collections">
	    <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Unity.Collections.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine">
	    <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.IMGUIModule">
	    <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.TextRenderingModule">
	    <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>